game_settings:
   spreadplayers:
      enable: true # True: when start the game, spread players.
      minimum_distance: 100 # for spreadplayer command, minimum distance between player = 100 * number of spreaded players, Default: 100
      maximum_area: 500 # for spreadplayer command, maximum area where a player can be teleported = 500 * number of spreaded players, must be > minimum_distance parameter, Default: 500
   saturation: true # True: give infinite saturation effect to all players
   rewards: true # True: give reward after each age
   start_time: 4 # minutes, Default: 4
   time_added: 2 # minutes added to start_time after each age, Default: 2
   block_per_age: 5 # number of block to complete to move to the next age, min: 1, Default: 5
   skip:
      enable: true # allow player to skip block if they are after 2nd block of current age, Default: true
      age: 2 # First age that allow skipping block, Default: 2
   custom_crafts: true # allow players to use custom crafts, Default: true
   see_block_count: true # allow players to know others player progress, Default: true
   keep_inventory: true # allow player to keep their inventory after death, Default: true