name: Kuffle
version: 3.3
author: KosmosUniverse
main: fr.kosmosuniverse.kuffle.KuffleMain
api-version: 1.15

commands:
   klist:
      usage: /<command> [reset | remove <Player name> | add <@a | Player name>]
      description: command to add/remove players to the list and view/reset the list
      permission: inferno.flagrate
   kstart:
      usage: /<command>
      description: command to start the game
      permission: inferno.flagrate
   kstop:
      usage: /<command>
      description: command to stop the game when it is running
      permission: inferno.flagrate
   kpause:
      usage: /<command>
      description: command to pause the game when it is running
      permission: inferno.flagrate
   kresume:
      usage: /<command>
      description: command to resume the game when it is paused
      permission: inferno.flagrate
   kvalidate:
      usage: /<command> <Player name>
      description: command to validate a block
      permission: inferno.flagrate
   kadminskip:
      usage: /<command> <Player name>
      description: command to skip a block for any player
      permission: inferno.flagrate
   kadminspawn:
      usage: /<command> <Multiblock name>
      description: command to spawn multiblock structure
      permission: inferno.flagrate
   kadminsave:
      usage: /<command>
      description: command to save and end the game of all players
      permission: inferno.flagrate
   kadminload:
      usage: /<command>
      description: command to load and start the game of all registered players
      permission: inferno.flagrate
   kback:
      usage: /<command>
      description: command to teleport back to death position
   kskip:
      usage: /<command>
      description: command to skip a block
   kcrafts:
      usage: /<command>
      description: command to see custom crafts
   kmultiblocks:
      usage: /<command>
      description: command to see multiBlocks
   kageblocks:
      usage: /<command>
      description: command to see current age blocks

permissions:
   klist:
      description: command to add players to the list and view the list
      default: op
   kstart:
      description: command to start the game
      default: op
   kstop:
      description: command to stop the game when it is running
      default: op
   kpause:
      description: command to pause the game when it is runnin
      default: op
   kresume:
      description: command to resume the game when it is paused
      default: op
   kvalidate:
      description: command to validate a block
      default: op
   kadminskip:
      description: command to skip a block for any player
      default: op
   kadminspawn:
      description: command to spawn multiblock structure
      default: op
   kadminsave:
      description: command to save and end the game of all players
      default: op
   kadminload:
      description: command to load and start the game of all registered players
      default: op
   kback:
      description: command to teleport back to death position
      default: true
   kskip:
      description: command to skip a block
      default: true
   kcrafts:
      description: command to see custom crafts
      default: true
   kmultiblocks:
      description: command to see multiBlocks
      default: true
   kageblocks:
      description: command to see current age blocks
      default: true